target:
	javac ../source/src/texaspoker/Card.java -d ../source/classes
	javac ../source/src/texaspoker/ActionMap.java -d ../source/classes
	javac ../source/src/texaspoker/HeadMeg.java -d ../source/classes
	javac ../source/src/texaspoker/State.java -d ../source/classes -classpath ../source/classes
	javac ../source/src/texaspoker/PreFlopAction.java -d ../source/classes	-classpath ../source/classes
	javac ../source/src/texaspoker/PostFlopAction.java -d ../source/classes -classpath ../source/classes
	javac ../source/src/texaspoker/HandPowerComputer.java -d ../source/classes -classpath ../source/classes
	javac ../source/src/texaspoker/HandleMeg.java -d ../source/classes